//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.Concrete.RolletRepository {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rollet", Namespace="http://schemas.datacontract.org/2004/07/DataAccess.Models")]
    [System.SerializableAttribute()]
    public partial class Rollet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OpenedPartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OpenedPart {
            get {
                return this.OpenedPartField;
            }
            set {
                if ((this.OpenedPartField.Equals(value) != true)) {
                    this.OpenedPartField = value;
                    this.RaisePropertyChanged("OpenedPart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RolletRepository.IRolletRepository")]
    public interface IRolletRepository {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRolletRepository/GetRollet", ReplyAction="http://tempuri.org/IRolletRepository/GetRolletResponse")]
        BusinessLogic.Concrete.RolletRepository.Rollet GetRollet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRolletRepository/GetRollet", ReplyAction="http://tempuri.org/IRolletRepository/GetRolletResponse")]
        System.Threading.Tasks.Task<BusinessLogic.Concrete.RolletRepository.Rollet> GetRolletAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRolletRepository/UpdateRollet", ReplyAction="http://tempuri.org/IRolletRepository/UpdateRolletResponse")]
        void UpdateRollet(BusinessLogic.Concrete.RolletRepository.Rollet rollet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRolletRepository/UpdateRollet", ReplyAction="http://tempuri.org/IRolletRepository/UpdateRolletResponse")]
        System.Threading.Tasks.Task UpdateRolletAsync(BusinessLogic.Concrete.RolletRepository.Rollet rollet);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRolletRepositoryChannel : BusinessLogic.Concrete.RolletRepository.IRolletRepository, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RolletRepositoryClient : System.ServiceModel.ClientBase<BusinessLogic.Concrete.RolletRepository.IRolletRepository>, BusinessLogic.Concrete.RolletRepository.IRolletRepository {
        
        public RolletRepositoryClient() {
        }
        
        public RolletRepositoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RolletRepositoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RolletRepositoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RolletRepositoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BusinessLogic.Concrete.RolletRepository.Rollet GetRollet() {
            return base.Channel.GetRollet();
        }
        
        public System.Threading.Tasks.Task<BusinessLogic.Concrete.RolletRepository.Rollet> GetRolletAsync() {
            return base.Channel.GetRolletAsync();
        }
        
        public void UpdateRollet(BusinessLogic.Concrete.RolletRepository.Rollet rollet) {
            base.Channel.UpdateRollet(rollet);
        }
        
        public System.Threading.Tasks.Task UpdateRolletAsync(BusinessLogic.Concrete.RolletRepository.Rollet rollet) {
            return base.Channel.UpdateRolletAsync(rollet);
        }
    }
}
