//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RolletApi.Concrete.RolletManager {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RolletBlo", Namespace="http://schemas.datacontract.org/2004/07/BusinessLogic.Models")]
    [System.SerializableAttribute()]
    public partial class RolletBlo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LighterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LighterStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RolletStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LighterId {
            get {
                return this.LighterIdField;
            }
            set {
                if ((this.LighterIdField.Equals(value) != true)) {
                    this.LighterIdField = value;
                    this.RaisePropertyChanged("LighterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LighterState {
            get {
                return this.LighterStateField;
            }
            set {
                if ((this.LighterStateField.Equals(value) != true)) {
                    this.LighterStateField = value;
                    this.RaisePropertyChanged("LighterState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RolletState {
            get {
                return this.RolletStateField;
            }
            set {
                if ((this.RolletStateField.Equals(value) != true)) {
                    this.RolletStateField = value;
                    this.RaisePropertyChanged("RolletState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RolletManager.IRolletManager")]
    public interface IRolletManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRolletManager/GetRollets", ReplyAction="http://tempuri.org/IRolletManager/GetRolletsResponse")]
        RolletApi.Concrete.RolletManager.RolletBlo[] GetRollets(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRolletManager/GetRollets", ReplyAction="http://tempuri.org/IRolletManager/GetRolletsResponse")]
        System.Threading.Tasks.Task<RolletApi.Concrete.RolletManager.RolletBlo[]> GetRolletsAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRolletManager/UpdateRollet", ReplyAction="http://tempuri.org/IRolletManager/UpdateRolletResponse")]
        void UpdateRollet(RolletApi.Concrete.RolletManager.RolletBlo rollet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRolletManager/UpdateRollet", ReplyAction="http://tempuri.org/IRolletManager/UpdateRolletResponse")]
        System.Threading.Tasks.Task UpdateRolletAsync(RolletApi.Concrete.RolletManager.RolletBlo rollet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRolletManager/ChangePosition", ReplyAction="http://tempuri.org/IRolletManager/ChangePositionResponse")]
        void ChangePosition(int id, int change);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRolletManager/ChangePosition", ReplyAction="http://tempuri.org/IRolletManager/ChangePositionResponse")]
        System.Threading.Tasks.Task ChangePositionAsync(int id, int change);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRolletManagerChannel : RolletApi.Concrete.RolletManager.IRolletManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RolletManagerClient : System.ServiceModel.ClientBase<RolletApi.Concrete.RolletManager.IRolletManager>, RolletApi.Concrete.RolletManager.IRolletManager {
        
        public RolletManagerClient() {
        }
        
        public RolletManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RolletManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RolletManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RolletManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RolletApi.Concrete.RolletManager.RolletBlo[] GetRollets(string email) {
            return base.Channel.GetRollets(email);
        }
        
        public System.Threading.Tasks.Task<RolletApi.Concrete.RolletManager.RolletBlo[]> GetRolletsAsync(string email) {
            return base.Channel.GetRolletsAsync(email);
        }
        
        public void UpdateRollet(RolletApi.Concrete.RolletManager.RolletBlo rollet) {
            base.Channel.UpdateRollet(rollet);
        }
        
        public System.Threading.Tasks.Task UpdateRolletAsync(RolletApi.Concrete.RolletManager.RolletBlo rollet) {
            return base.Channel.UpdateRolletAsync(rollet);
        }
        
        public void ChangePosition(int id, int change) {
            base.Channel.ChangePosition(id, change);
        }
        
        public System.Threading.Tasks.Task ChangePositionAsync(int id, int change) {
            return base.Channel.ChangePositionAsync(id, change);
        }
    }
}
