//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.Concrete.UserRepository {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/DataAccess.Models")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserRepository.IUserRepository")]
    public interface IUserRepository {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRepository/Get", ReplyAction="http://tempuri.org/IUserRepository/GetResponse")]
        BusinessLogic.Concrete.UserRepository.User Get(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRepository/Get", ReplyAction="http://tempuri.org/IUserRepository/GetResponse")]
        System.Threading.Tasks.Task<BusinessLogic.Concrete.UserRepository.User> GetAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRepository/Post", ReplyAction="http://tempuri.org/IUserRepository/PostResponse")]
        void Post(BusinessLogic.Concrete.UserRepository.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRepository/Post", ReplyAction="http://tempuri.org/IUserRepository/PostResponse")]
        System.Threading.Tasks.Task PostAsync(BusinessLogic.Concrete.UserRepository.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserRepositoryChannel : BusinessLogic.Concrete.UserRepository.IUserRepository, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserRepositoryClient : System.ServiceModel.ClientBase<BusinessLogic.Concrete.UserRepository.IUserRepository>, BusinessLogic.Concrete.UserRepository.IUserRepository {
        
        public UserRepositoryClient() {
        }
        
        public UserRepositoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserRepositoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserRepositoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserRepositoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BusinessLogic.Concrete.UserRepository.User Get(string email) {
            return base.Channel.Get(email);
        }
        
        public System.Threading.Tasks.Task<BusinessLogic.Concrete.UserRepository.User> GetAsync(string email) {
            return base.Channel.GetAsync(email);
        }
        
        public void Post(BusinessLogic.Concrete.UserRepository.User user) {
            base.Channel.Post(user);
        }
        
        public System.Threading.Tasks.Task PostAsync(BusinessLogic.Concrete.UserRepository.User user) {
            return base.Channel.PostAsync(user);
        }
    }
}
